query AuthDataLocal {
    authDataLocal @client {
        accessToken
        accessTokenExpiration
        refreshToken
        refreshTokenExpiration
        user {
            id
            username
            role
        }
    }
}
