query Characters($skip: Int, $limit: Int, $characterFilters: CharacterFilters) {
    characters(skip: $skip, limit: $limit, characterFilters: $characterFilters) {
        id
        name
        imageUrl
        gender
        seasons {
           number
        }
    }
}
